//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theatrix.Theatrix.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Theatrix.Services.IVideoService")]
    public interface IVideoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoService/GetVideoById", ReplyAction="http://tempuri.org/IVideoService/GetVideoByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object GetVideoById(string videoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoService/GetVideoById", ReplyAction="http://tempuri.org/IVideoService/GetVideoByIdResponse")]
        System.Threading.Tasks.Task<object> GetVideoByIdAsync(string videoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoService/GetVideosByKeyword", ReplyAction="http://tempuri.org/IVideoService/GetVideosByKeywordResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetVideosByKeyword(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoService/GetVideosByKeyword", ReplyAction="http://tempuri.org/IVideoService/GetVideosByKeywordResponse")]
        System.Threading.Tasks.Task<object[]> GetVideosByKeywordAsync(string keyword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVideoServiceChannel : Theatrix.Services.IVideoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VideoServiceClient : System.ServiceModel.ClientBase<Theatrix.Services.IVideoService>, Theatrix.Services.IVideoService {
        
        public VideoServiceClient() {
        }
        
        public VideoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VideoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VideoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VideoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object GetVideoById(string videoId) {
            return base.Channel.GetVideoById(videoId);
        }
        
        public System.Threading.Tasks.Task<object> GetVideoByIdAsync(string videoId) {
            return base.Channel.GetVideoByIdAsync(videoId);
        }
        
        public object[] GetVideosByKeyword(string keyword) {
            return base.Channel.GetVideosByKeyword(keyword);
        }
        
        public System.Threading.Tasks.Task<object[]> GetVideosByKeywordAsync(string keyword) {
            return base.Channel.GetVideosByKeywordAsync(keyword);
        }
    }
}
